Add bind keys
Flutterando/auto_injector pull request #13
Opened 2023-08-23 14:32 UTC by davidsdearaujo

## What does this PR do
It creates a way to add and get binds by a **String** key.

Now **all** the **add** and **get** methods have a `String? key` parameter.

> **Search functions:** 
> When [key] is provided it will search the instance that have the same key

> **Add functions:**
> When [key] is provided this instance only can be found by key

## Changed Functions:
```dart
  T get<T>({ParamTransform? transform, String? key});

  T call<T>({ParamTransform? transform, String? key});

  void add<T>(Function constructor, {BindConfig<T>? config, String? key});

  void addInstance<T>(T instance, {BindConfig<T>? config, String? key});

  void addSingleton<T>(Function constructor, { BindConfig<T>? config, String? key});

  void addLazySingleton<T>(Function constructor, {BindConfig<T>? config, String? key});

  dynamic getNotifier<T>({String? key});

  T? tryGet<T>({ParamTransform? transform, String? key});

  bool isAdded<T>({String? key});

  bool isInstantiateSingleton<T>({String? key});

  T? disposeSingleton<T>({String? key});

  void replaceInstance<T>(T instance, {String? key});
```

2023-08-23 15:23 UTC, jacobaraujo7 requested changes
Can you add some tests about this case?

2023-08-23 15:23 UTC, jacobaraujo7 commented on lib/src/bind.dart
> +        className: (key != null) ? null : classNameString,
```suggestion
        className: key ?? classNameString,
```

2023-08-23 15:41 UTC, toshiossada commented
LGTM

2023-08-23 15:45 UTC, davidsdearaujo commented
> @jacobaraujo7
> Can you add some tests about this case?

The entire [auto_injector_tag_test.dart](https://github.com/Flutterando/auto_injector/pull/13/files#diff-a571f67bacf291119af78defb8dedc61efa78355ad32c1ad7bf2de4ced3939ac) is testing it!

2023-08-23 15:49 UTC, davidsdearaujo commented
> @jacobaraujo7
> Can you add some tests about this case?

The entire [test/src/auto_injector_with_key_test.dart](https://github.com/Flutterando/auto_injector/pull/13/files#diff-61add6ae205229a44b6a4e064ecb7a8f3101c3a17570422f75786721c6991fc2) is testing it!

2023-08-23 17:00 UTC, toshiossada reviewed
LGFM

2023-08-24 01:27 UTC, jacobaraujo7 approved these changes

2023-08-24 01:27 UTC, merged